-- Sample data for testing (replace with actual user IDs from your auth system)
-- These are example records - in production, user_id should match auth.uid()

INSERT INTO interactions (user_id, question, answer, summary, confidence, mode, image_url, audio_url) VALUES
('demo-user-1', 'What is the capital of France?', 'The capital of France is Paris. It is one of the most beautiful cities in the world, known for the Eiffel Tower, Louvre Museum, and romantic atmosphere.', 'Paris is the capital of France', 0.95, 'text', null, null),
('demo-user-1', 'How do I cook pasta perfectly?', 'To cook pasta perfectly, use a large pot with plenty of water, add salt when water boils, cook according to package instructions until al dente, and save some pasta water before draining.', 'Guide for cooking perfect pasta', 0.88, 'voice', null, 'https://example.com/audio/pasta-cooking.mp3'),
('demo-user-1', 'Can you identify this plant?', 'This appears to be a Monstera deliciosa, commonly known as the Swiss cheese plant. It has large, glossy, heart-shaped leaves with natural holes called fenestrations.', 'Monstera deliciosa plant identification', 0.92, 'camera', 'https://example.com/images/monstera.jpg', null),
('demo-user-1', 'What are the benefits of meditation?', 'Meditation offers numerous benefits including stress reduction, improved focus, better emotional regulation, enhanced self-awareness, and potentially lower blood pressure and improved sleep quality.', 'Meditation provides mental and physical health benefits', 0.89, 'text', null, null),
('demo-user-1', 'How do I fix a leaky faucet?', 'To fix a leaky faucet, first turn off the water supply, disassemble the handle, replace worn washers or O-rings, clean any mineral deposits, and reassemble everything tightly.', 'Steps to fix a leaky faucet', 0.85, 'voice', null, 'https://example.com/audio/faucet-repair.mp3'),
('demo-user-1', 'What breed is this dog?', 'This appears to be a Golden Retriever, known for their friendly temperament, beautiful golden coat, and intelligence. They make excellent family pets and are often used as service dogs.', 'Golden Retriever dog breed identification', 0.94, 'camera', 'https://example.com/images/golden-retriever.jpg', null),
('demo-user-1', 'What is machine learning?', 'Machine learning is a subset of artificial intelligence that enables systems to learn and improve from experience without being explicitly programmed. It uses algorithms to analyze data, identify patterns, and make decisions.', 'Machine learning is AI that learns from data', 0.91, 'text', null, null),
('demo-user-1', 'How can I improve my public speaking?', 'To improve public speaking, practice regularly, know your audience, structure your speech clearly, use visual aids, maintain eye contact, speak clearly and at a good pace, and manage anxiety through breathing techniques.', 'Tips for better public speaking skills', 0.87, 'voice', null, 'https://example.com/audio/public-speaking.mp3'),
('demo-user-1', 'What type of cloud is this?', 'This appears to be a cumulus cloud, characterized by its puffy, cotton-like appearance with flat bases. These are fair weather clouds that typically indicate good weather conditions.', 'Cumulus cloud identification', 0.83, 'camera', 'https://example.com/images/cumulus-cloud.jpg', null),
('demo-user-1', 'What are the main differences between Python and JavaScript?', 'Python is known for simplicity and readability, often used in data science and backend development. JavaScript is primarily for web development, runs in browsers, and has asynchronous capabilities. Python uses indentation for blocks, while JavaScript uses curly braces.', 'Python vs JavaScript comparison', 0.93, 'text', null, null);